#!/usr/bin/env python3
"""
analyze.py -- turn the cells into the owner's deliverables (sections 18 and 20).

    python3 evidence_to_draft_pilot/analyze.py

Writes, under the experiment root and OUTSIDE git:
    variants/<subject>/PRE_EDIT.md, A.md, B.md, C.md      the actual drafts
    variants/<subject>/PATCHES.json                       accepted and rejected edits
    RESULTS.json                                          the per-subject/per-arm table
    SUMMARY.md                                            the human-readable summary

WHAT IT REFUSES TO DO. It does not aggregate the deterministic checks into a publication
verdict, it does not settle a reviewer disagreement, and it does not call a partial
evaluation ALL_GATES_PASS. Sections 17 and 19: the checks that ran are named, the ones
that did not are named, and every count is reported with its denominator.
"""
from __future__ import annotations

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
AUTOMATION = HERE.parent
if str(AUTOMATION) not in sys.path:
    sys.path.insert(0, str(AUTOMATION))

from evidence_to_draft_pilot import arms as AR                     # noqa: E402
from evidence_to_draft_pilot import budget as BU                   # noqa: E402
from evidence_to_draft_pilot import origin as OR                   # noqa: E402

ROOT = pathlib.Path("/srv/data/cripminds-new-engine-v1/experiments/"
                    "evidence-to-draft-pilot")

BANNER = ("<!-- NOT_PUBLISHABLE_EXPERIMENT. Generated by the evidence-to-draft pilot "
          "from retained evidence. Not reviewed by the owner, not fact-checked by the "
          "authoritative tail, and not for publication. -->\n\n")


def load_manifest():
    return json.loads((ROOT / "EXPERIMENT_MANIFEST.json").read_text())


def load_subject(run):
    return json.loads((ROOT / "subjects" / run / "SUBJECT.json").read_text())


def write_variants(ledger: BU.Ledger, run: str) -> dict:
    """Persist the actual prose, plus the patch record. Returns the per-subject row."""
    d = ROOT / "variants" / run
    d.mkdir(parents=True, exist_ok=True)
    subj = load_subject(run)
    gi = subj["generation_inputs"]
    row = {"subject_id": run, "subject": subj["subject"], "split": subj["split"],
           "plan_contract": subj.get("plan_contract"),
           "source_set_hash": subj["source_set_hash"],
           "ledger_sha256": subj["ledger_sha256"],
           "plan_sha256": subj["plan_sha256"],
           "languages": subj["languages"], "arms": {}}

    w = ledger.load_cell("%s:writer" % run)
    if not w or w["status"] != "OK":
        row["writer"] = {"status": (w or {}).get("status", "MISSING"),
                         "error": (w or {}).get("error_text")}
        return row
    wr = w["result"]
    draft = wr["article_text"]
    (d / "PRE_EDIT.md").write_text(BANNER + draft)
    row["writer"] = {"status": "OK", "words": wr["words"],
                     "sha256": AR.CP.C.sha256_text(draft),
                     "calls": w["provider_calls_issued"],
                     "seconds": w["elapsed_seconds"]}
    row["shared_pre_edit_sha256"] = AR.CP.C.sha256_text(draft)

    patches = {}
    for arm in ("A", "B", "C"):
        c = ledger.load_cell("%s:%s" % (run, arm))
        if not c:
            row["arms"][arm] = {"status": "NOT_RUN"}
            continue
        if c["status"] != "OK":
            row["arms"][arm] = {"status": "ERROR", "error": c.get("error_text"),
                                "calls": c.get("provider_calls_issued")}
            continue
        r = c["result"]
        text = r.get("article_text")
        a = {"status": r.get("status", "PASS"), "calls": c["provider_calls_issued"],
             "seconds": c["elapsed_seconds"], "words": r.get("words")}
        if arm == "A":
            a["continuity"] = r.get("continuity")
            a["prose_finish"] = r.get("prose_finish")
        if arm in ("B", "C") and r.get("editor"):
            e = r["editor"]
            a["editor_status"] = e["status"]
            a["edits_proposed"] = e["proposed"]
            a["edits_accepted"] = len(e["accepted_patches"])
            a["edits_rejected"] = len(e["rejected_patches"])
            a["batch_accepted"] = e["accepted"]
            a["combined_delta_errors"] = e["combined_delta_errors"]
            # Section 18: were the prior bytes preserved when the edit was refused?
            a["prior_bytes_preserved_on_rejection"] = (
                None if e["accepted"]
                else text == (draft if arm == "B" else r.get("pre_edit_text", text)))
            patches[arm] = {"accepted": e["accepted_patches"],
                            "rejected": e["rejected_patches"],
                            "combined_delta_errors": e["combined_delta_errors"]}
        if arm == "C":
            a["planner_status"] = r.get("planner_status")
            a["pre_edit_words"] = r.get("pre_edit_words")
        if text:
            (d / ("%s.md" % arm)).write_text(BANNER + text)
            a["sha256"] = AR.CP.C.sha256_text(text)
            # The deterministic checks, applied identically to every variant that has a
            # comparable packet. C has its own packet because it has its own plan.
            try:
                if arm in ("A", "B"):
                    chk = AR.deterministic_checks(
                        variant_text=text, draft_text=draft, packet=wr["packet"],
                        arch=gi["architecture"], ledger=gi["ledger"], cut=wr["cut"],
                        lineage=wr["negative_lineage_verified"])
                else:
                    chk = AR.deterministic_checks(
                        variant_text=text, draft_text=text, packet=r["writer_packet"],
                        arch=None, ledger=gi["ledger"], cut=r["cut"],
                        lineage=r["negative_lineage_verified"])
                a["deterministic_checks"] = chk
            except Exception as exc:                               # noqa: BLE001
                a["deterministic_checks_error"] = str(exc)[:200]
        row["arms"][arm] = a

    # DISCIPLINED OMISSION vs A THIN ARTICLE (owner's distinction, measured not judged).
    #
    # C is not to be rewarded merely for using fewer facts: a sparse plan trivially
    # reduces factual risk. The separation needs two numbers that move independently --
    # how much evidence the arm actually carried, and how much evidence the blind
    # reviewers said the article NEEDED and dropped. Fewer facts with few needed-omission
    # flags is discipline; fewer facts with many is thinness. Neither number is a verdict
    # and the report prints both rather than a ratio.
    row["evidence_load"] = {
        "ledger_facts": subj["ledger_facts"],
        "retained_plan_use_facts": len(gi["architecture"].get("use_facts") or []),
        "retained_plan_beats": len(gi["architecture"].get("beats") or []),
        "note": "A and B draft the retained plan, so their evidence load is the "
                "retained plan's. Only C selects its own.",
    }

    p = ledger.load_cell("%s:plan" % run)
    if p and p["status"] == "OK":
        pr = p["result"]
        row["plan"] = {"status": pr["status"],
                       "c_contract": pr.get("c_contract"),
                       "calls": p["provider_calls_issued"],
                       "facts_kept": pr.get("facts_kept"),
                       "beats": pr.get("beats"),
                       "beats_in_retained_plan": pr.get("beats_in_retained_plan"),
                       "facts_in_retained_plan": pr.get("facts_in_retained_plan"),
                       "historical_plan_compatible":
                           pr.get("historical_plan_compatible"),
                       "architecture_errors": pr.get("architecture_errors"),
                       "derivation_notes": pr.get("derivation_notes")}
        plan_obj = pr.get("plan") or {}
        row["plan"]["international_reader_context"] = \
            plan_obj.get("international_reader_context") or []
        row["plan"]["missing_or_disputed"] = plan_obj.get("missing_or_disputed") or []
        row["plan"]["distinct_reading"] = plan_obj.get("distinct_reading")
        (d / "PLAN.json").write_text(json.dumps(pr, indent=1, ensure_ascii=False))
    elif p:
        row["plan"] = {"status": "ERROR", "error": p.get("error_text")}

    if patches:
        (d / "PATCHES.json").write_text(json.dumps(patches, indent=1,
                                                   ensure_ascii=False))
        if pr.get("status") == "PASS":
            row["evidence_load"]["c_use_facts"] = pr.get("facts_kept")
            row["evidence_load"]["c_beats"] = pr.get("beats")

    rev = ROOT / "reviews" / ("%s.json" % run)
    if rev.exists():
        rv = json.loads(rev.read_text())
        row["review"] = rv["reconciliation"]
        # The needed-omission signal, per arm, from both reviewers. Counted, not scored.
        omitted = {}
        for who in ("claude", "codex"):
            for arm, v in ((rv.get(who) or {}).get("by_arm") or {}).items():
                omitted.setdefault(arm, {})[who] = len(
                    v.get("useful_evidence_omitted") or [])
        row["needed_evidence_omitted_flags"] = omitted

        # TASK 3: where each reported defect actually came from. Deterministic.
        a_txt = (ledger.load_cell("%s:A" % run) or {}).get("result") or {}
        b_txt = (ledger.load_cell("%s:B" % run) or {}).get("result") or {}
        row["failure_origin"] = OR.classify_subject(
            draft=draft,
            a_text=a_txt.get("article_text") or "",
            b_text=b_txt.get("article_text") or "",
            reviews={w: rv.get(w) for w in ("claude", "codex") if rv.get(w)})
    return row


def main():
    man = load_manifest()
    ledger = BU.Ledger(ROOT / "ledger")
    rows = []
    for run in man["development_subjects"] + man["held_out_subjects"]:
        rows.append(write_variants(ledger, run))

    results = {
        "pilot": "evidence-to-draft-pilot",
        "not_publishable": "NOT_PUBLISHABLE_EXPERIMENT",
        "budget": ledger.summary(),
        "checks_that_ran": ["composition.safety_audit (deterministic)",
                            "continuity.semantic_delta (deterministic)",
                            "composition.check_architecture on every derived plan"],
        "checks_that_did_not_run": ["grounding", "authoritative fact check",
                                    "claim mapper", "reader gate",
                                    "editorial package", "publication bridge"],
        "this_is_not_all_gates_pass": True,
        "subjects": rows,
    }
    (ROOT / "RESULTS.json").write_text(json.dumps(results, indent=1,
                                                  ensure_ascii=False))
    print(json.dumps(ledger.summary(), indent=1))
    for r in rows:
        arms = r.get("arms") or {}
        print("\n%s  [%s]  %s" % (r["subject_id"][-8:], r["split"],
                                  r["subject"][:48]))
        print("   writer: %s" % json.dumps(r.get("writer")))
        for a in ("A", "B", "C"):
            if a in arms:
                print("   %s: %s" % (a, json.dumps(arms[a])[:260]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
